version: '3.8'
services:
  db:
      container_name: ztl_db
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      volumes:
        - ./node/src/sql/db.sql:/docker-entrypoint-initdb.d/db.sql
  app:
    container_name: node_app_ztl
    build: ./node
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  